### ISSUE TITLE
not able to install python3-venv 

### ISSUE THREAD

**Issue by omprakashsonie** [talonvoice/wav2train#1]
while running ./wfilter 

I am using machine in Azure which is based on Linux and followed Debian instructions

**Comment by lunixbochs** [comment]
Sorry, I'm not providing support for random linux distributions. Both ubuntu and debian appear to have this package in every recent release:

https://packages.debian.org/search?keywords=python3-venv
https://packages.ubuntu.com/search?keywords=python3-venv

Use an ubuntu or debian distro, or you'll need to figure out how to install the dependencies on your own.

**Comment by omprakashsonie** [comment]
Thanks Ryan.
