### ISSUE TITLE
issue while executing wav2train and wfilter

### ISSUE THREAD

**Issue by omprakashsonie** [talonvoice/wav2train#2]
Hi Ryan,
I am working with this toy dataset:

~/wav2train-2/wav2train/data$ ls -l
    193 Jul 13 19:40 clips.lst
   4096 Jul 13 19:40 sa11.lst
     54 Jul 13 19:40 sa11.txt
  94618 Jul 13 19:40 sa11.wav
     45 Jul 13 19:40 sa12.txt
  70042 Jul 13 19:40 sa12.wav
     78 Jul 13 19:40 sa13.txt
 116736 Jul 13 19:40 sa13.wav
     60 Jul 13 19:40 sa14.txt
  99944 Jul 13 19:40 sa14.wav
     54 Jul 13 19:40 sa15.txt
  91956 Jul 13 19:40 sa15.wav

after executing: 
./wav2train data/ data_o/

~/wav2train-2/wav2train/data_o$ ls -l

 4096 Jul 13 19:46 align
 4096 Jul 13 19:46 clips
    0 Jul 13 19:46 clips.lst

clips.lst has no entry and clips/ is empty

=================================
for ./wfilter

toy dataset
(base) omprakash.s@liv-dev29:~/wav2train-2/wav2train$ ls -lt data_flac
total 592
     53 Jul 13 19:49 head-filt.lst
 102689 Jul 13 19:43 app_1097501295_3562626254953775104.flac
  81591 Jul 13 19:43 app_1407135996_3599519540775485440.flac
 157981 Jul 13 19:43 app_1907322960_3665496302440939520.flac
 121214 Jul 13 19:43 app_820535199_3576599499079942144.flac
 125434 Jul 13 19:43 app_865791490_3592299299968385024.flac

~/wav2train-2/wav2train$ cat data_flac/head.lst
app_820535199_3576599499079942144 /home/omprakash.s/wav2train-2/wav2train/data_flac/app_820535199_3576599499079942144.flac 4019.9999999999995 text1
app_1097501295_3562626254953775104 /home/omprakash.s/wav2train-2/wav2train/data_flac/app_1097501295_3562626254953775104.flac 2880.0 text2
app_1407135996_3599519540775485440 /home/omprakash.s/wav2train-2/wav2train/data_flac/app_1407135996_3599519540775485440.flac 2460.0 text3
app_1907322960_3665496302440939520 /home/omprakash.s/wav2train-2/wav2train/data_flac/app_1907322960_3665496302440939520.flac 4440.0 text4
app_865791490_3592299299968385024 /home/omprakash.s/wav2train-2/wav2train/data_flac/app_865791490_3592299299968385024.flac 3960.0 text5

after executing:
~/wav2train-2/wav2train$ ./wfilter data_flac/head.lst 0.5 > data_flac/filtered.lst

getting msg:
"Usage: wfilter w2l_dir/ clips.lst 0.5 > filtered.lst" in file
~/wav2train-2/wav2train$ cat data_flac/filtered.lst

even after limiting jobs and workers to 1:
~/wav2train-2/wav2train$ ./wfilter data_flac/ head.lst 0.5 > data_flac/filtered.lst --jobs 1 --workers 1
~/wav2train-2/wav2train$ cat data_flac/filtered.lst
Usage: wfilter w2l_dir/ clips.lst 0.5 > filtered.lst

getting same message
~/wav2train-2/wav2train$ ./wfilter data_flac/ head.lst 0.5 > data_flac/filtered.lst --jobs 1 --workers 1
~/wav2train-2/wav2train$ cat data_flac/filtered.lst
Usage: wfilter w2l_dir/ clips.lst 0.5 > filtered.lst

Will really appreciate any pointers to what am I missing.

**Comment by lunixbochs** [comment]
You ran:
```
$ ./wfilter data_flac/head.lst 0.5
```

Usage is:
```
Usage: wfilter w2l_dir/ clips.lst 0.5 > filtered.lst
```

wfilter depends on a wav2letter model and library that aren't downloaded automatically. Instructions for getting it are in this comment: https://github.com/facebookresearch/wav2letter/issues/509#issuecomment-580970765

Run wav2train with -v, my guess is it failed to align anything.

**Comment by lunixbochs** [comment]
There's an example dataset in this comment that successfully aligns: https://github.com/facebookresearch/wav2letter/issues/509#issuecomment-580883545

Your audio is english right?

**Comment by omprakashsonie** [comment]
Thanks Ryan. It is not English.

./wfilter -v data_flac/   head.lst 0.5 > data_flac/filtered.lst
still stores msg "Usage: wfilter w2l_dir/ clips.lst 0.5 > filtered.lst" in file data_flac/filtered.lst

As I have flac files and lst so I am interested in making sure wav2letter doesn't core dump as it did with (loadSound error). Any debug message/log to identify the file which threw error is good too.

**Comment by omprakashsonie** [comment]
Also, for other language the link you mentioned in issue:
https://github.com/facebookresearch/wav2letter/issues/509

>> See here: https://github.com/mozilla/DSAlign/blob/master/align/wavTranscriber.py#L28

is not working.

**Comment by lunixbochs** [comment]
Again:
```
Usage: wfilter w2l_dir/ clips.lst 0.5 > filtered.lst
```

You asked about both wav2train and wfilter. I linked a comment with a specific wfilter example, then said to run the wav2train command with -v. You ran the wfilter command instead with -v and did not appear to follow the comment I linked.

**Comment by lunixbochs** [comment]
DSAlign primarily works on english. I'm not currently interested in providing extremely hands on support for this.

Please attempt to follow the working examples such as this: https://github.com/facebookresearch/wav2letter/issues/509#issuecomment-580883545
and this: https://github.com/facebookresearch/wav2letter/issues/509#issuecomment-580970765

Please don't ask further questions without first reading the code and getting an understanding of what's happening.

**Comment by lunixbochs** [comment]
If you're just trying to fix the loadSound issue, use wvalid, not wfilter.

wfilter runs a wav2letter model against your audio and filters out poor character matches. wvalid just tries to load the audio and filters out ones that don't load.

**Comment by omprakashsonie** [comment]
Thanks Ryan for your help. I had gone through your suggestions. As I mentioned I had audio files and lst files so didn't need wav2train. Hence I tried with -v option with wfilter.

Sure will try wvalid.

Thank you again Ryan.
