### ISSUE TITLE
'OverflowError('cannot serialize a bytes object larger than 4 GiB',)'

### ISSUE THREAD

**Issue by jpmcarrilho** [talonvoice/wav2train#4]
Hello, first, thanks for such an useful repo!

I created a dataset with +- 10GB and 24k utterances. When I run ./wav2train I get the following error:
`
[+] Starting new alignment.
[+] Input: /dataset
[+] Output: /wav2train/train_data
[+] Collecting files to align
[+] Aligning (23842) transcript(s)
Align:   0%|                                         | 0/23842 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/wav2train/src/wav2train.py", line 235, in <module>
    wav2train(args)
  File "/wav2train/src/wav2train.py", line 205, in wav2train
    for audio_path, aligned_path, txt_path in tqdm(align_iter, desc='Align', total=len(align_queue)):
  File "/wav2train/DSAlign/venv/lib/python3.6/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 347, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f8d1c749358>'. Reason: 'OverflowError('cannot serialize a bytes object larger than 4 GiB',)'
`
While doing some research I found this StackOverflow: https://stackoverflow.com/questions/51562221/python-multiprocessing-overflowerrorcannot-serialize-a-bytes-object-larger-t/51568084

But I'm in doubt about how to insert this piece correctly in my code. Any guidance would be helpful, thanks!

**Comment by jpmcarrilho** [comment]
When adding to wav2train.py the before mentioned `pickle4reducer.py`, and importing it on the beginning of the file with:
`
ctx = multiprocessing.get_context()
ctx.reducer = pickle4reducer.Pickle4Reducer()
`
I get: 
`
[+] Starting new alignment.
[+] Input: /dataset
[+] Output: /wav2train/train_data
[+] Collecting files to align
[+] Aligning (23842) transcript(s)
Align:   0%|                                         | 0/23842 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/wav2train/src/wav2train.py", line 238, in <module>
    wav2train(args)
  File "/wav2train/src/wav2train.py", line 208, in wav2train
    for audio_path, aligned_path, txt_path in tqdm(align_iter, desc='Align', total=len(align_queue)):
  File "/wav2train/DSAlign/venv/lib/python3.6/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 347, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f6201f9a780>'. Reason: 'MemoryError()'
`

**Comment by lunixbochs** [comment]
Nothing in that iterator should be 4GB. It’s basically just file paths. Try forcing chunksize=1, and forcing jobs to 1

**Comment by jpmcarrilho** [comment]
Still getting exactly the same 4gb error

**Comment by lunixbochs** [comment]
I maintain something else is terribly wrong, we are only sending file paths (both ways) through the iterator, and only a few of them per iteration. I have used wav2train on a 96 core machine against millions of clips and terabytes of audio in a single job.

**Comment by jpmcarrilho** [comment]
You were right, I found a corrupted file with extremely large size in the middle of my dataset.

**Comment by lunixbochs** [comment]
Was it audio or text? I'm still not sure how that would have manifested as this error.

**Comment by jpmcarrilho** [comment]
4/5GB of unreadable text.
