### ISSUE TITLE
Install wav2train on Ubuntu?

### ISSUE THREAD

**Issue by ML6634** [talonvoice/wav2train#5]
May one install/use wav2train on Ubuntu (20.04)? Thanks.

**Comment by lunixbochs** [comment]
Have you tried?

**Comment by ML6634** [comment]
Not yet. However, I noticed that Ubuntu was not listed. So, has anybody tried or not?

**Comment by lunixbochs** [comment]
ubuntu is based on Debian

**Comment by ML6634** [comment]
I got:
<pre>$ ./setup
bash: ./setup: No such file or directory
</pre>

Do I need to install DSAlign first? Thanks.

**Comment by lunixbochs** [comment]
There's a file called setup in the repository folder. This is not really the place to ask for help with basic Linux or git usage, sorry.
